### ISSUE TITLE
你好，我用options.data 绑定数据，数据更新重新设置(new vue).options.data,但是数据没有重新刷新？

### ISSUE THREAD

**Issue by xmllein** [wenzhixin/vue-bootstrap-table#1]

**Comment by wenzhixin** [comment]
谢谢反馈，将 `columns` 和 `data` 从 options 提取出来作为 props 了：https://jsfiddle.net/wenyi/nhog9hxb/2/.

**Comment by wenzhixin** [comment]
文档在这里：http://vue-bootstrap-table.wenzhixin.net.cn/documentation/properties/
