### ISSUE TITLE
Vue2 Compatibility

### ISSUE THREAD

**Issue by joshua1** [wenzhixin/vue-bootstrap-table#16]
Hi @wenzhixin is this compatible with version 2 ?

Hi @wenzhixin是与版本2兼容吗？

**Comment by wenzhixin** [comment]
现在不兼容

**Comment by joshua1** [comment]
任何计划，使其兼容

**Comment by joshua1** [comment]
我现在使用简单的引导库。 工作确定  
i am using the plain bootstrap library at the moment. works ok

**Comment by LiveLikeCounter** [comment]
Hi @wenzhixin , have you plans to make ik compatible with Vue2?

**Comment by lordroseman** [comment]
yeah, please make it compatible to Vue2, your bootstrap table is awesome

**Comment by ananthachetan** [comment]
Looking forward to it.

**Comment by wenzhixin** [comment]
Please use:
https://bootstrap-table.com/docs/vuejs/introduction/
https://github.com/wenzhixin/bootstrap-table
