### ISSUE TITLE
requirejs

### ISSUE THREAD

**Issue by clemsontiger** [wenzhixin/vue-bootstrap-table#17]
do you have an example of how to get this to work with requirejs?

I'm getting: 

[Vue warn]: Unknown custom element: <bootstrap-table> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in <Root>)

http://codepen.io/paul/pen/YZLpyZ

**Comment by wenzhixin** [comment]
Please use:
https://bootstrap-table.com/docs/vuejs/introduction/
https://github.com/wenzhixin/bootstrap-table
