### ISSUE TITLE
search组件No matching records found,pagnition没有reset

### ISSUE THREAD

**Issue by fengxueye** [wenzhixin/vue-bootstrap-table#18]
hi，wenzhixin 你在 https://jsfiddle.net/wenyi/nhog9hxb/1/    给出的demo 里我将options设置如下
options: {
      pagination:true,
      pageSize:2,
      search:true
    }
serarchText=9 搜不出结果，页码和showingRows也没重设

**Comment by wenzhixin** [comment]
Please use:
https://bootstrap-table.com/docs/vuejs/introduction/
https://github.com/wenzhixin/bootstrap-table
