### ISSUE TITLE
请求用全链接时候出现，出现options请求，我是跨域的。

### ISSUE THREAD

**Issue by xmllein** [wenzhixin/vue-bootstrap-table#2]
解决方案：修改contentType:'application/x-www-form-urlencoded; charset=UTF-8',
建议在文档上注明一下，折腾一个早上。

**Comment by wenzhixin** [comment]
http://vue-bootstrap-table.wenzhixin.net.cn/documentation/table-options/#contenttype:d680e8a854a7cbad6d490c445cba2eba

你看下文档，默认是：`'application/json'`

**Comment by xmllein** [comment]
是，我也是看了文档才醒悟了，所以建议，你在文档有更加详细说明，避免像我这样粗心的人。

**Comment by wenzhixin** [comment]
OK，谢谢建议。

**Comment by wenzhixin** [comment]
这个插件才开发了一周左右，现在还在继续开发和完善中。
还有很多需要完善的地方，你假如有什么问题或者建议都可以提出来 :)
