### ISSUE TITLE
使用 column 属性 formatter时候 返回值 ，直接就该变数据值的值，导致在分页的时候解析错误

### ISSUE THREAD

**Issue by xmllein** [wenzhixin/vue-bootstrap-table#3]

**Comment by wenzhixin** [comment]
麻烦提供下 jsfiddle

**Comment by xmllein** [comment]
你有qq，加你，给你看看

**Comment by xmllein** [comment]
我的qq：214271581

**Comment by wenzhixin** [comment]
基于： https://jsfiddle.net/wenyi/nhog9hxb/1/

**Comment by xmllein** [comment]
这个jsfiddle 好慢

**Comment by xmllein** [comment]
https://jsfiddle.net/wenyi/nhog9hxb/1/，你看看这个，下一页是没有问题，但是返回上一页，时间数据就报错了

**Comment by xmllein** [comment]
看到了？

**Comment by wenzhixin** [comment]
你没用 Update？跟我发的链接是一样的

**Comment by xmllein** [comment]
https://jsfiddle.net/nhog9hxb/11/ 
这个，刚刚忘了update

**Comment by xmllein** [comment]
https://jsfiddle.net/nhog9hxb/12/
还有这个，event 不起作用

**Comment by wenzhixin** [comment]
应该是 bug，我有空修复下。

**Comment by xmllein** [comment]
好纠结，项目正在进行中...

**Comment by wenzhixin** [comment]
formatter 的问题已经修复：https://jsfiddle.net/nhog9hxb/11/

**Comment by wenzhixin** [comment]
events 的问题也已经修复

**Comment by xmllein** [comment]
挺快，谢谢

**Comment by wenzhixin** [comment]
记得给我加个 star :)
