### ISSUE TITLE
 同时使用height 和  sort 的时候会出现表头和底部对不齐的情况

### ISSUE THREAD

**Issue by qbaty** [wenzhixin/vue-bootstrap-table#8]
而且滚动条也会消失。
这个版本是不是未完成？

```
options: { 
  class: 'table table-hover table-striped',
  sortStable: true,
  height: 200
}
```

**Comment by wenzhixin** [comment]
能否提供下 [jsfiddle](https://github.com/wenzhixin/vue-bootstrap-table#jsfiddle)？

**Comment by qbaty** [comment]
有可以直接引用的cdn 的 vue-bootstrap-table地址吗？

**Comment by qbaty** [comment]
https://jsfiddle.net/qbaty/nhog9hxb/41/

而且npm 上封装的也有问题，依赖 jquery 什么都没有import ，直接npm install 是不能用的
另外问一个问题，原版的 bootstrap-table 是怎么保证fixed 的头部和 底部的列宽相等的？是保证每个单元格等宽么？

可否直接借助 css 的 fixed 来实现呢？就不需要限制等宽了

**Comment by wenzhixin** [comment]
因为还在开发，目前还不支持 npm 的方式，后面也会去掉 jQuery 的依赖。

**Comment by qbaty** [comment]
能否先回答一下上面的问题？目前是有问题吧？
我的项目想用，感觉功能的确比较强大
现在主流浏览器对jquery 的依赖很小了，应该可以方便的去掉
上面的例子是有bug 吧？能否解决一下？另外更新一下npm 的包？至少保持和 github 一致？

**Comment by qbaty** [comment]
现在主流浏览器对jquery 的依赖很小了，应该可以方便的去掉

**Comment by wenzhixin** [comment]
发现 npm 上是被别人发布了：https://www.npmjs.com/package/vue-bootstrap-table ，那个作者不是我，而且也没有看到他有开源到 github 上。。

**Comment by wenzhixin** [comment]
你可以先不用 height，这里还没有完善好。bootstrap-table 的实现方式你可以看下： http://wenzhixin.net.cn/2014/08/10/fixed_table

**Comment by qbaty** [comment]
看了你说的三种方式，你理解了我说的方式么？
可以直接让 thead position:fixed，如果担心底下的tbody 顶上来，可以先在thead 内部clone 一次，占位
比如：

```
<thead class="fixed">
  <tr></tr>
<thead>
<thead>
  <tr></tr>
</thead>
```

我的需求如果不用height ，我就不用过来给你发issue 了，而且不用fixed 表头，我可不用第三方的插件啊
那是不是说vue-bootstrap-table 还占时不可用啊，至少某些功能上

**Comment by qbaty** [comment]
npm 上发布的人不是作者么？怪不得啊

**Comment by wenzhixin** [comment]
是的，有些功能还在开发中，例如你说的这个，毕竟要移植过来也要些时间。
发布的不是本人。

**Comment by wenzhixin** [comment]
Please use:
https://bootstrap-table.com/docs/vuejs/introduction/
https://github.com/wenzhixin/bootstrap-table
